# Generated by Django 3.0 on 2019-12-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('act_name', models.CharField(blank=True, max_length=50, null=True)),
                ('act_date', models.DateField(primary_key=True, serialize=False)),
                ('attend_list', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckinList',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkin_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('deparement', models.CharField(blank=True, max_length=50, null=True)),
                ('stu_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('identity', models.IntegerField()),
            ],
            options={
                'db_table': 'club_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendList',
            fields=[
                ('act', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Check_in_System.ClubMember')),
            ],
            options={
                'db_table': 'activity_attend_list',
                'managed': False,
            },
        ),
    ]
